<?php

/**
 * @file
 * Contains hugs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hugs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hugs module.
    case 'help.page.hugs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hugs') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hugs_theme() {
  $theme['hug_page'] = [
    'variables' => ['from' => NULL, 'to' => NULL],
    'template' => 'hug_page',
  ];

  return $theme;
}
